@startuml detail_tugas

title Detail Tugas
skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor User
participant "Task Manager" as TM
control Controller
database Database

User -> TM: Buka Halaman Detail Tugas
TM -> Controller: Permintaan Ambil Informasi Tugas
Controller -> Database: Ambil Informasi Tugas
Database --> Controller: Informasi Tugas
Controller --> TM: Informasi Tugas
TM --> User: Tampilkan Detail Tugas

@enduml